# Project information

site_name: Deploying a React Application using AWS Amplify
site_description: 
#site_author: 'beralfon@amazon.com'
site_url: 'http://aws-react-amplify.ws.kabits.com'

# Repository
#repo_name: 'aws-samples/aws-security-workshops'
repo_url: 'https://github.com/aurbac/aws-react-amplify'

google_analytics: ['UA-55517703-9', 'aws-react-amplify.ws.kabits.com']

# Copyright
copyright: '<a href="https://aws.amazon.com/privacy/" target="blank">Privacy</a> | <a href="https://aws.amazon.com/terms/" target="blank">Site terms</a> | &copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

extra:
  social: 
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aurbac
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aurbac
    - icon: fontawesome/solid/home
      link: http://aws-msg-app.ws.kabits.com

nav:
    - Home: index.md
    - Preparing your development environment: preparing-your-development-environment.md
    - Adding Authentication: adding-authentication.md
    - Adding Analytics: adding-analytics.md
    - Creating a GraphQL API: adding-api.md
    - Adding Storage: adding-storage.md
    - Add Translate Text and Text to Speech: adding-predictions.md
    - Adding Hosting: adding-hosting.md

theme:
  name: material
  palette:
    primary: amber
    accent: amber
  icon:
    logo: fontawesome/brands/aws
    repo: fontawesome/brands/git-alt
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg